name: Compile on iOS

run-name: 📱 iOS Build - ${{ github.event.head_commit.message }}

on:
  push:
    branches: [ develop ]
    paths-ignore:
      - ".gitignore"
      - "README.md"
      # ignore CI for other platforms
      - ".github/workflows/android.yml"
      - ".github/workflows/api.yml"
      - ".github/workflows/linux.yml"
      - ".github/workflows/macos.yml"

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - name: Checkout Enroute
      uses: actions/checkout@v4
      with:
        path: enroute
        submodules: recursive
        fetch-depth: 0
    - name: Set up macOS
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install Ninja
      run: brew install ninja
    - name: Install Qt for Desktop
      uses: jurplel/install-qt-action@v4
      with:
        cache: 'true'
        cache-key-prefix: 'install-qt-action-macOS-host'
        version: '6.8.0'
        modules: 'qt5compat qtconnectivity qthttpserver qtimageformats qtlocation qtmultimedia qtpositioning qtshadertools qtspeech qtwebsockets qtwebview'
    - name: Set QT_HOST_PATH
      run: |
        echo QT_HOST_PATH=$QT_ROOT_DIR >> $GITHUB_ENV
    - name: Install Qt for iOS
      uses: jurplel/install-qt-action@v4
      with:
        cache: 'true'
        cache-key-prefix: 'install-qt-action-iOS'
        target: 'ios'
        version: '6.8.0'
        modules: 'qt5compat qtconnectivity qthttpserver qtimageformats qtlocation qtmultimedia qtpositioning qtshadertools qtsensors qtspeech qtwebsockets qtwebview'
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: macos
    - name: Compile Enroute Flight Navigation
      run: |
        $QT_ROOT_DIR/bin/qt-cmake \
          -B build-enroute \
          -S enroute \
          -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_C_COMPILER_LAUNCHER="ccache" \
          -DCMAKE_CXX_COMPILER_LAUNCHER="ccache" \
          -DCMAKE_INSTALL_PREFIX=.
        cmake --build build-enroute -- -sdk iphonesimulator
